### ISSUE TITLE
La página no está al día

### ISSUE THREAD

**Issue by pedro-bonilla** [MicrosoftDocs/sql-docs.es-es#47]
La versión 18.2 lleva una semana disponible en la pagina original (en-us), y en esta aún no está.. 
https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sqlallproducts-allversions#download-ssms-182

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Descargar SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/es-es/sql/ssms/download-sql-server-management-studio-ssms?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.es-es/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @pedro-bonilla
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @pedro-bonilla

Gracias por sus comentarios. 

El equipo de ingeniería ha revisado las sugerencias y las ha aceptado. Hemos implementado sus comentarios y los hemos publicado en los artículos actualizados del sitio de Docs en las siguientes páginas: https://docs.microsoft.com/es-es/sql/ssms/download-sql-server-management-studio-ssms?view=sqlallproducts-allversions#feedback

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios. 

Atentamente, 

Equipo internacional de Microsoft Docs
