### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by yecarri** [MicrosoftDocs/sql-docs.es-es#52]
This link is broken: https://go.microsoft.com/fwlink/?linkid=2104251

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Descargar SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/es-es/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.es-es/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @yecarri
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by dnethi** [comment]
Please get the latest from here - https://docs.microsoft.com/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017

**Comment by lichasu** [comment]
Hello, @yecarri 
 
Thank you for your feedback.
 
The link will automatically be implemented in the next localization round.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team

**Comment by yecarri** [comment]
That link leads to the same page that doesn't work. Did you try the linki
yourself?

[image: image.png]

**Comment by dnethi** [comment]
the fwd link is https://go.microsoft.com/fwlink/?linkid=2105412 which is different from what you had in your original post.

**Comment by yecarri** [comment]
[image: image.png]
