### ISSUE TITLE
El link de descarga está roto para el idioma Español (España)

### ISSUE THREAD

**Issue by pauer24** [MicrosoftDocs/sql-docs.es-es#54]
Lo dicho, el link de descarga está roto para el idioma Español (España)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Descargar SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/es-es/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.es-es/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @pauer24
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hola @pauer24 

El link va a ser actualizado automáticamente. El link funciona correctamente en la página en inglés.

Muchas gracias por su contribución.
