### ISSUE TITLE
Enlace roto

### ISSUE THREAD

**Issue by rodolforeinafigueroa** [MicrosoftDocs/sql-docs.es-es#55]
El siguiente enlace no descarga el SSMS:
https://go.microsoft.com/fwlink/?linkid=2104251
Pagina origen:
https://docs.microsoft.com/es-es/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Descargar SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/es-es/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.es-es/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @rodolforeinafigueroa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by rodolforeinafigueroa** [comment]
Thank you for you answer. 
I'll be attentive to the case.

Best regards,
Rodolfo Reina

**Comment by jfranpino** [comment]
Sigue sin funcionar el enlace roto, podéis arreglarlo?
Gracias.

**Comment by CeciAc** [comment]
Hola @jfranpino 
Este es un problema globalque afecta a varias páginas y estamos trabajando en su resolución

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by yecarri** [comment]
https://go.microsoft.com/fwlink/?linkid=2105412

**Comment by CeciAc** [comment]
Hola @jfranpino

Gracias por sus comentarios. 

El equipo de ingeniería ha revisado las sugerencias y las ha aceptado. Hemos implementado sus comentarios y los hemos publicado en los artículos actualizados del sitio de Docs en las siguientes páginas: https://docs.microsoft.com/es-es/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios. 

Atentamente, 

Equipo internacional de Microsoft Docs
