### ISSUE TITLE
Descargas primero

### ISSUE THREAD

**Issue by Apocatastasis** [MicrosoftDocs/sql-docs.es-es#67]
Pongan los links de descarga primero, no todos tenemos tiempo para leer sus release notes y darnos cuenta que se encuentran a la mitad.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Descargar SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/es-es/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.es-es/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by CeciAc** [comment]
Hola, @Apocatastasis

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://docs.microsoft.com/es-es/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
