### ISSUE TITLE
conexion entre nodos

### ISSUE THREAD

**Issue by Aligtrrz** [MicrosoftDocs/sql-docs.es-es#73]
Ante todo, un cordial saludo, estuve siguiendo el tutorial y todo marchaba bien hasta el punto n° 5 de la creación de suscriptores, al intentar agregar un suscriptor de SQL Server, el agente no me lo permite. (Cabe destacar que el suscriptor es un servidor remoto) me gustaría saber donde puedo conseguir la documentación para lograr la conexión de los dos nodos, tal como lo muestran en este tutorial.
Otra acotación, es que a través de la IP del servidor, logro conectar la instancia en el publicador pero no logro conectarlo como suscriptor.
Mucho sabre agradecer su atención.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 0086945e-a60b-31ed-9445-160fed6ea1f1
* Version Independent ID: 2dcdbf33-d5af-b766-dd5c-f477c8b441b7
* Content: [Tutorial: Configuración de la replicación entre dos servidores conectados completamente (transaccional) - SQL Server](https://docs.microsoft.com/es-es/sql/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers?view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers.md](https://github.com/MicrosoftDocs/sql-docs.es-es/blob/live/docs/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by srvbpigh** [comment]
Hello, @Aligtrrz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @Aligtrrz 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí:  https://github.com/MicrosoftDocs/sql-docs/issues/3543

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by Aligtrrz** [comment]
Gracias, estaré atento. Espero poder conseguir la solución.
