### ISSUE TITLE
Configuracion de Alertas SQL DATA

### ISSUE THREAD

**Issue by rxriveraRR** [MicrosoftDocs/sql-docs.es-es#75]
COnfiguracion

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: d4626315-3b47-273d-a2b7-a2ebb94b1592
* Version Independent ID: 156f8421-d9b4-c125-f20e-e4a92bb98289
* Content: [Configurar una alerta de base de datos de SQL Server (Windows) - SQL Server](https://docs.microsoft.com/es-es/sql/relational-databases/performance/set-up-a-sql-server-database-alert-windows?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/performance/set-up-a-sql-server-database-alert-windows.md](https://github.com/MicrosoftDocs/sql-docs.es-es/blob/live/docs/relational-databases/performance/set-up-a-sql-server-database-alert-windows.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by srvbpigh** [comment]
Hello, @rxriveraRR
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @rxriveraRR 

Valoramos enormemente su comentario y estamos haciendo todo lo posible por mejorar su experiencia en docs.microsoft.com. No obstante, necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?  

Atentamente, 

Equipo internacional de Microsoft DOCS

**Comment by V-vafune** [comment]
Hola, @rxriveraRR: 

Esta es una continuación de nuestro comentario anterior. Necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario? 

Atentamente, 

Equipo internacional de Microsoft DOCS

**Comment by CeciAc** [comment]
Hola, @rxriveraRR:

Gracias nuevamente por su comentario. 

Lamentablemente, aún nos falta información y no podemos procesar sus comentarios. En este momento, cerraremos este problema de GitHub, pero le animamos a enviar más comentarios en el futuro. 

Atentamente, 

Equipo internacional de Microsoft DOCS
