### ISSUE TITLE
Typo in order of command mssql-conf

### ISSUE THREAD

**Issue by albertoRamon** [MicrosoftDocs/sql-docs.es-es#80]
HI, I think this is a typo (check the order)

"sudo ACCEPT_EULA='Y' MSSQL_PID='Developer' MSSQL_SA_PASSWORD='<YourStrong!Passw0rd>' MSSQL_TCP_PORT=1234 /opt/mssql/bin/mssql-conf setup"

Must be:  Sudo command parameters
OR
SetEnvironment sudo command

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b12eac8a-8797-b2d4-5195-e1d77b4b0001
* Version Independent ID: 163b4b50-6e25-b006-6ea6-c6e4cfd044d0
* Content: [Configuración de variables de entorno para SQL Server en Linux - SQL Server](https://docs.microsoft.com/es-es/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15&source=docs)
* Content Source: [docs/linux/sql-server-linux-configure-environment-variables.md](https://github.com/MicrosoftDocs/sql-docs.es-es/blob/live/docs/linux/sql-server-linux-configure-environment-variables.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hey @amvin87 - Do you mind checking this?

#reassign:amvin87

**Comment by amvin87** [comment]
This looks to be correct, we are setting the environment variables and then running the config of SQL Server. @albertoRamon do you see any errors when running the command. Could you explain more please

**Comment by albertoRamon** [comment]
Yes, It´s correct

Thanks
